/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_abasto;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setTitle("BocApp");
        this.setLocationRelativeTo(null);
//        rsscalelabel.RSScaleLabel.setScaleLabel(lblImg1, "src/imagenes/Plano 1.png");
//        rsscalelabel.RSScaleLabel.setScaleLabel(lblImg2, "src/imagenes/Plano 2.png");
//        rsscalelabel.RSScaleLabel.setScaleLabel(lblImg3, "src/imagenes/Plano 3.png");
//        rsscalelabel.RSScaleLabel.setScaleLabel(lblImg4, "src/imagenes/Plano 4.png");
//        rsscalelabel.RSScaleLabel.setScaleLabel(lblImg5, "src/imagenes/Plano 5.png");
    }
    /*Datos de entrada*/
    String qCaudal_s, qProm_s,qmaximo_s, pendiente_i_s, coe_descarga_s, cota_entrega_s, barrotes_s, a_separacion_s, fondoRio_s;
    double qCaudal, qProm, qmaximo, pendiente_i, coe_descarga, cota_entrega, barrotes, a_separacion, fondoRio;
    /*DATOS*/
    double h_diseño, laterales=1, correc_laterales, v_rio, Xs, Xi, B, area_neta, v_barrotes=0.1, longi_rejilla, n_ori, profun_aguas_abajo/*he*/, profun_critica/*hc*/, 
            profun_aguas_arriba/*ho*/, He, H0, longi_canal, bordeLibre=0.15, vel_agua_final, B_camara, h_muros, H /*modificar el nombre*/, q_captado, q_exce, H_exce, V_exce;
    /*CALCULO DE COTAS*/    
    double diseño, maxima, promedio, corona_muros_contencion, fondo_aguas_arriba, fondo_aguas_abajo, lamina_aguas_arriba, lamina_aguas_abajo, Cresta_vertedero_excesos, fondo, cota_entrada, 
            cota_salida;
    
    public static double redondearDecimales(double valorInicial, int numeroDecimales) {
        double parteEntera, resultado;
        resultado = valorInicial;
        parteEntera = Math.floor(resultado);
        resultado=(resultado-parteEntera)*Math.pow(10, numeroDecimales);
        resultado=Math.round(resultado);
        resultado=(resultado/Math.pow(10, numeroDecimales))+parteEntera;
        return resultado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPendiente_i = new javax.swing.JTextField();
        txtQprom = new javax.swing.JTextField();
        txtQ = new javax.swing.JTextField();
        txtCoe_descarga = new javax.swing.JTextField();
        txtCota_entrega = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSeparacion = new javax.swing.JTextField();
        cmbTamaBarrotes = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtQmax = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFondoRio = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblDato2 = new javax.swing.JLabel();
        lblDato1 = new javax.swing.JLabel();
        lblImg1 = new javax.swing.JLabel();
        lblImg2 = new javax.swing.JLabel();
        lblImg3 = new javax.swing.JLabel();
        lblImg4 = new javax.swing.JLabel();
        lblImg5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 4300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        jLabel6.setText("Coeficiente de descarga (Cd):");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 209, -1, -1));

        jLabel7.setText("Cota del río en la entrega:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 239, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 6, 120, -1));

        jLabel2.setText("Datos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 65, -1, -1));

        jLabel3.setText("Caudal (Q):");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 87, -1, -1));

        jLabel4.setText("Caudal promedio (Qprom):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, -1, -1));

        jLabel5.setText("Pendiente del fondo del canal (i):");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 179, -1, -1));

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 381, -1, -1));

        txtPendiente_i.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPendiente_iKeyTyped(evt);
            }
        });
        jPanel1.add(txtPendiente_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 175, 84, -1));

        txtQprom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQpromKeyTyped(evt);
            }
        });
        jPanel1.add(txtQprom, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 109, 84, -1));

        txtQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQActionPerformed(evt);
            }
        });
        txtQ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQKeyTyped(evt);
            }
        });
        jPanel1.add(txtQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 79, 84, -1));

        txtCoe_descarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCoe_descargaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCoe_descarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 205, 84, -1));

        txtCota_entrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCota_entregaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCota_entrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 235, 84, -1));

        jLabel8.setText("Tamaño de barrotes:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 270, -1, -1));

        jLabel9.setText("Separación entre barrotes:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 307, -1, -1));

        txtSeparacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeparacionKeyTyped(evt);
            }
        });
        jPanel1.add(txtSeparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 303, 84, -1));

        cmbTamaBarrotes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/2\"" }));
        cmbTamaBarrotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTamaBarrotesActionPerformed(evt);
            }
        });
        jPanel1.add(cmbTamaBarrotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 265, 84, -1));

        jLabel10.setText("cm.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 307, -1, -1));

        jLabel11.setText("L/s");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 83, -1, -1));

        jLabel12.setText("%");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 179, -1, -1));

        jLabel13.setText("Caudal maximo (Qmax):");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 143, -1, -1));

        txtQmax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQmaxKeyTyped(evt);
            }
        });
        jPanel1.add(txtQmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 139, 84, -1));

        jLabel14.setText("m3/s");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 113, -1, -1));

        jLabel15.setText("m3/s");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 143, -1, -1));

        jLabel16.setText("Fondo del rio en la captación:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 343, -1, -1));

        txtFondoRio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFondoRioKeyTyped(evt);
            }
        });
        jPanel1.add(txtFondoRio, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 339, 84, -1));

        jLabel17.setText("m.");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 343, -1, -1));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 6, -1, -1));

        jLabel18.setText("Fecha:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 10, -1, -1));

        jLabel19.setText("m.");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 239, -1, -1));

        lblDato2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblDato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, 40, 30));
        jPanel1.add(lblDato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 710, 40, 20));

        lblImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plano 1.png"))); // NOI18N
        lblImg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1260, 720));

        lblImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plano 2.png"))); // NOI18N
        lblImg2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1190, 1260, 720));

        lblImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plano 3.png"))); // NOI18N
        lblImg3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1930, 1260, 720));

        lblImg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plano 4.png"))); // NOI18N
        lblImg4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2670, 1260, 720));

        lblImg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plano 5.png"))); // NOI18N
        lblImg5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3410, 1260, 720));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setText("Generar PDF");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1047, 4190, 180, 50));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 4294, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtQ.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor del caudal de diseño.");
        }else if (txtSeparacion.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca la separación entre barrotes.");
        }else if(txtPendiente_i.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca la pendiente del fondo del canal.");
        }else if(txtQmax.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor del caudal maximo.");
        }else if(txtQprom.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor del caudal promedio.");
        }else if(txtCoe_descarga.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor del coeficiente de descarga.");
        }else if(txtCota_entrega.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor de la Cota de entrega.");
        }else if(txtFondoRio.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor del fondo del río.");
        }else{
            qCaudal_s= txtQ.getText();
            qCaudal = Double.parseDouble(qCaudal_s);
            qCaudal = qCaudal/1000.0;
            
            barrotes_s = (String) cmbTamaBarrotes.getSelectedItem();
            if(barrotes_s.equals("1/2\"")){
                barrotes = 0.0127;
            }else{
                barrotes = 0;
            }
            
            a_separacion_s = txtSeparacion.getText();
            a_separacion = Double.parseDouble(a_separacion_s);
            a_separacion = a_separacion /100.0;   
            
            pendiente_i_s = txtPendiente_i.getText();
            pendiente_i = Double.parseDouble(pendiente_i_s);
            pendiente_i = pendiente_i / 100.0;
            
            qmaximo_s = txtQmax.getText();
            qmaximo = Double.parseDouble(qmaximo_s);
            
            qProm_s = txtQprom.getText();
            qProm = Double.parseDouble(qProm_s);
            
            coe_descarga_s = txtCoe_descarga.getText();
            coe_descarga = Double.parseDouble(coe_descarga_s);
            
            cota_entrega_s = txtCota_entrega.getText();
            cota_entrega = Double.parseDouble(cota_entrega_s);
            
            fondoRio_s = txtFondoRio.getText();
            fondoRio = Double.parseDouble(fondoRio_s);
            
            /* profun lamina de agua */
            h_diseño = Math.pow((qCaudal / 1.84 * laterales), (2.0/3.0));
            System.out.println("H: " + h_diseño);
            
            /* correción contracciones */
            correc_laterales = laterales - 0.2 * h_diseño;
            System.out.println("L': " + correc_laterales);
            
            /*velocidad del río sobre la presa*/
            v_rio = qCaudal / (correc_laterales * h_diseño); 
            System.out.println("V: "+v_rio);
            
            if(0.3<v_rio && v_rio<3.0){
                System.out.println("ok");
                Xs = 0.36 * Math.pow(v_rio,(2.0/3.0)) + 0.6 * Math.pow(h_diseño,(4.0/7.0));
                Xi = 0.18 * Math.pow(v_rio,(4.0/7.0)) + 0.74 * Math.pow(h_diseño,(3.0/4.0));
                B = Xs + 0.1;
                double B_ceil = redondearDecimales(B, 1);
                System.out.println("Xs: " + Xs);
                System.out.println("Xi: " + Xi);
                System.out.println("B: " + B_ceil);
                
                area_neta = qCaudal / (0.9 * v_barrotes);
                longi_rejilla = (area_neta * (a_separacion + barrotes)) / (a_separacion * B_ceil);
                if(longi_rejilla<0.7){
                    longi_rejilla = 0.7;
                }   
                
                /*Recalcular area neta*/               
                double area_neta_2 = (a_separacion / (a_separacion+barrotes)) * B_ceil * longi_rejilla; //posible error en la var barrotes
                n_ori = area_neta_2 / (a_separacion*B_ceil);
                n_ori = Math.ceil(n_ori);
                System.out.println("numero de orificios: " + n_ori);
                double area_neta_3 = a_separacion * B_ceil * n_ori;
                area_neta_3 = redondearDecimales(area_neta_3, 3);
                double v_barrotes_2 = qCaudal / (0.9 * area_neta_3);
                double longi_rejilla_2 = (area_neta_3 * (a_separacion + barrotes)) / (a_separacion * B_ceil);
                System.out.println("v_barrotes_2: " + v_barrotes_2);
                System.out.println("longi_rejilla_2: " + longi_rejilla_2);
                
                /*Niveles de agua*/
                longi_canal = longi_rejilla_2 + 0.3/*dato del ppt*/;
                profun_aguas_abajo = Math.pow((Math.pow(qCaudal, 2.0)/ (9.81 * Math.pow(B_ceil, 2.0))),(1.0/3.0));
                profun_critica = profun_aguas_abajo;
                profun_aguas_arriba = Math.pow((2 * Math.pow(profun_aguas_abajo, 2.0) + Math.pow(profun_aguas_abajo - (pendiente_i * longi_canal / 3.0),2.0)), (1.0/2.0)) - (2.0/3.0) * pendiente_i*longi_canal;
                System.out.println("he: " + profun_aguas_abajo);
                System.out.println("ho: " + profun_aguas_arriba);
                
                /*ALTURA TOTAL DE LOS MUROS DEL CANAL DE ADUCCION*/
                H0 = profun_aguas_arriba + bordeLibre;
                He = profun_aguas_abajo + (profun_aguas_arriba - profun_aguas_abajo) + pendiente_i * longi_canal + bordeLibre;
                System.out.println("H0: " + H0);
                System.out.println("He: " + He);
                
                vel_agua_final = qCaudal / (B_ceil * profun_aguas_abajo);
                if(0.3<vel_agua_final && vel_agua_final<3.0){
                    /*DISEÑO DE LA CÁMARA DE RECOLECCIÓN*/
                    double Xs_2 = 0.36 * Math.pow(vel_agua_final, (2.0/3.0)) + 0.6 * Math.pow(profun_aguas_abajo, (4.0/7.0));
                    double Xi_2 = 0.18 * Math.pow(vel_agua_final,(4.0/7.0)) + 0.74 * Math.pow(profun_aguas_abajo, (3.0/4.0));
                    B_camara = Xs_2 + 0.3;
                    if(B_camara<1.5){
                        B_camara = 1.5;
                    }
                    System.out.println("Xs_2: " + Xs_2);
                    System.out.println("Xi_2: " + Xi_2);
                    System.out.println("B_camara: " + B_camara);
                    
                    /*ALTURA DE LOS MUROS DE CONTENCIÓN*/
                    h_muros = Math.pow((qmaximo / (1.84 * laterales)), (2.0/3.0));
                    h_muros = Math.ceil(h_muros);
                    System.out.println("H_muros: " + h_muros);
                    
                    /*CAUDAL DE EXCESOS*/
                    H = Math.pow((qProm / 1.84 * laterales), (2.0/3.0));
                    q_captado = coe_descarga * area_neta_3 * Math.sqrt(2 * 9.81 * H);                     
                    q_exce = q_captado - qCaudal;
                    System.out.println("q_exce: " + q_exce);
                    
                    /*CONDICIONES EN EL VERTEDERO DE EXCESOS*/
                    H_exce = Math.pow((q_exce / (1.84 * B_camara)),(2.0/3.0));
                    V_exce = q_exce / (H_exce * B_camara);
                    double e_Xs_esos = 0.36 * Math.pow(V_exce, (2.0/3.0)) + 0.6 * Math.pow(H_exce, (4.0/7.0)); 
                    System.out.println("e_Xs_esos: " + e_Xs_esos);
                    
                    /*CALCULO DE COTAS*/
                    /*lamina sobre la presa*/
                    diseño = fondoRio + h_diseño;
                    maxima = fondoRio + h_muros;
                    promedio = fondoRio + H;
                    /*Corona de los muros de contención*/ /*FALTA UNA VARIABLE?*/
                    //corona_muros_contencion = 100 + ;
                    /*Canal de aducción*/
                    fondo_aguas_arriba = fondoRio - H0;
                    fondo_aguas_abajo = fondoRio - He;
                    lamina_aguas_arriba = (fondoRio - H0) + profun_aguas_arriba;
                    lamina_aguas_abajo = (fondoRio - He) + profun_aguas_abajo;
                    /*Camara de recolección*/
                    Cresta_vertedero_excesos = fondoRio - He - bordeLibre;
                    fondo = fondoRio - He - bordeLibre - 0.6;
                    /*Tuberia de excesos*/
                    cota_entrada = fondo;
                    cota_salida = cota_entrega + coe_descarga/*es esta variablñe correcta?*/;
                    
                    /*CALCULO TUBERIA DE EXCESOS*/
                    double j = (cota_entrada - cota_salida) / 50;
                    double d = Math.pow((q_exce / (0.2785 * /*C*/100 * Math.pow(j, 0.54))),(1.0/2.63)); //que es C?? por ahora es 100
                    d = d * 39.3701;
                    System.out.println("d\":" + d);
                    
                    
                    /*PONER DATOS EN LA IMAGEN*/
                    lblDato1.setText(d+"");
                    lblDato2.setText(cota_salida+"");
                }else{
                    JOptionPane.showMessageDialog(null,"Velocidad del agua al final del canal inferior o superior a la esperada.");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Velocidad del rio inferior o superior a la esperada.");
            }
            
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbTamaBarrotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTamaBarrotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTamaBarrotesActionPerformed

    private void txtQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQActionPerformed
    }//GEN-LAST:event_txtQActionPerformed

    private void txtQKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQKeyTyped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo numeros");
        }
    }//GEN-LAST:event_txtQKeyTyped

    private void txtQpromKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQpromKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo numeros");
        }
    }//GEN-LAST:event_txtQpromKeyTyped

    private void txtQmaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQmaxKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo numeros");
        }
    }//GEN-LAST:event_txtQmaxKeyTyped

    private void txtPendiente_iKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPendiente_iKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo numeros");
        }
    }//GEN-LAST:event_txtPendiente_iKeyTyped

    private void txtCoe_descargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoe_descargaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo numeros");
        }
    }//GEN-LAST:event_txtCoe_descargaKeyTyped

    private void txtCota_entregaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCota_entregaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo numeros");
        }
    }//GEN-LAST:event_txtCota_entregaKeyTyped

    private void txtSeparacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeparacionKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo numeros");
        }
    }//GEN-LAST:event_txtSeparacionKeyTyped

    private void txtFondoRioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFondoRioKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo numeros");
        }
    }//GEN-LAST:event_txtFondoRioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTamaBarrotes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDato1;
    private javax.swing.JLabel lblDato2;
    private javax.swing.JLabel lblImg1;
    private javax.swing.JLabel lblImg2;
    private javax.swing.JLabel lblImg3;
    private javax.swing.JLabel lblImg4;
    private javax.swing.JLabel lblImg5;
    private javax.swing.JTextField txtCoe_descarga;
    private javax.swing.JTextField txtCota_entrega;
    private javax.swing.JTextField txtFondoRio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPendiente_i;
    private javax.swing.JTextField txtQ;
    private javax.swing.JTextField txtQmax;
    private javax.swing.JTextField txtQprom;
    private javax.swing.JTextField txtSeparacion;
    // End of variables declaration//GEN-END:variables
}
