/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_abasto;

import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setTitle("");
        this.setLocationRelativeTo(null);       
    }
    String qCaudal_s, qProm_s,qmaximo_s, pendiente_i_s, coe_descarga_s, cota_entrega_s, barrotes_s, a_separacion_s;
    double qCaudal, qProm, qmaximo, pendiente_i, coe_descarga, cota_entrega, barrotes, a_separacion;
    double h_diseño, laterales=1, correc_laterales, v_rio, Xs, Xi, B, area_neta, v_barrotes=0.1, longi_rejilla, n_ori, profun_aguas_abajo/*he*/, profun_critica/*hc*/, 
            profun_aguas_arriba/*ho*/, He, H0, longi_canal, bordeLibre=0.15, vel_agua_final, B_camara, H_muros, H /*modificar el nombre*/, q_captado, q_exce, H_exce, V_exce;
    
    public static double redondearDecimales(double valorInicial, int numeroDecimales) {
        double parteEntera, resultado;
        resultado = valorInicial;
        parteEntera = Math.floor(resultado);
        resultado=(resultado-parteEntera)*Math.pow(10, numeroDecimales);
        resultado=Math.round(resultado);
        resultado=(resultado/Math.pow(10, numeroDecimales))+parteEntera;
        return resultado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPendiente_i = new javax.swing.JTextField();
        txtQprom = new javax.swing.JTextField();
        txtQ = new javax.swing.JTextField();
        txtCoe_descarga = new javax.swing.JTextField();
        txtCota_entrega = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSeparacion = new javax.swing.JTextField();
        cmbTamaBarrotes = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtQmax = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel6.setText("Coeficiente de descarga (Cd):");

        jLabel7.setText("Cota del río en la entrega:");

        jLabel2.setText("Datos:");

        jLabel3.setText("Caudal (Q):");

        jLabel4.setText("Caudal promedio (Qprom):");

        jLabel5.setText("Pendiente del fondo del canal (i):");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Tamaño de barrotes:");

        jLabel9.setText("Separación entre barrotes:");

        cmbTamaBarrotes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/2\"" }));
        cmbTamaBarrotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTamaBarrotesActionPerformed(evt);
            }
        });

        jLabel10.setText("cm.");

        jLabel11.setText("L/s");

        jLabel12.setText("%");

        jLabel13.setText("Caudal maximo (Qmax):");

        jLabel14.setText("m3/s");

        jLabel15.setText("m3/s");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbTamaBarrotes, javax.swing.GroupLayout.Alignment.LEADING, 0, 84, Short.MAX_VALUE)
                                .addComponent(txtCota_entrega))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCoe_descarga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(txtPendiente_i, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQprom, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQ, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQmax))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSeparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(145, 145, 145)
                                .addComponent(jButton1)))))
                .addContainerGap(900, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQprom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSeparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPendiente_i, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCoe_descarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCota_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbTamaBarrotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)))
                .addContainerGap(425, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1244, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtQ.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor del caudal de diseño.");
        }else if (txtSeparacion.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca la separación entre barrotes.");
        }else if(txtPendiente_i.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca la pendiente del fondo del canal.");
        }else if(txtQmax.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor del caudal maximo.");
        }else if(txtQprom.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor del caudal promedio.");
        }else{
            qCaudal_s= txtQ.getText();
            qCaudal = Double.parseDouble(qCaudal_s);
            qCaudal = qCaudal/1000.0;
            
            barrotes_s = (String) cmbTamaBarrotes.getSelectedItem();
            if(barrotes_s.equals("1/2\"")){
                barrotes = 0.0127;
            }else{
                barrotes = 0;
            }
            
            a_separacion_s = txtSeparacion.getText();
            a_separacion = Double.parseDouble(a_separacion_s);
            a_separacion = a_separacion /100.0;   
            
            pendiente_i_s = txtPendiente_i.getText();
            pendiente_i = Double.parseDouble(pendiente_i_s);
            pendiente_i = pendiente_i / 100.0;
            
            qmaximo_s = txtQmax.getText();
            qmaximo = Double.parseDouble(qmaximo_s);
            
            qProm_s = txtQprom.getText();
            qProm = Double.parseDouble(qProm_s);
            
            coe_descarga_s = txtCoe_descarga.getText();
            coe_descarga = Double.parseDouble(coe_descarga_s);
            
            /* profun lamina de agua */
            h_diseño = Math.pow((qCaudal / 1.84 * laterales), (2.0/3.0));
            System.out.println("H: " + h_diseño);
            
            /* correción contracciones */
            correc_laterales = laterales - 0.2 * h_diseño;
            System.out.println("L': " + correc_laterales);
            
            /*velocidad del río sobre la presa*/
            v_rio = qCaudal / (correc_laterales * h_diseño); 
            System.out.println("V: "+v_rio);
            
            if(0.3<v_rio && v_rio<3.0){
                System.out.println("ok");
                Xs = 0.36 * Math.pow(v_rio,(2.0/3.0)) + 0.6 * Math.pow(h_diseño,(4.0/7.0));
                Xi = 0.18 * Math.pow(v_rio,(4.0/7.0)) + 0.74 * Math.pow(h_diseño,(3.0/4.0));
                B = Xs + 0.1;
                double B_ceil = redondearDecimales(B, 1);
                System.out.println("Xs: " + Xs);
                System.out.println("Xi: " + Xi);
                System.out.println("B: " + B_ceil);
                
                area_neta = qCaudal / (0.9 * v_barrotes);
                longi_rejilla = (area_neta * (a_separacion + barrotes)) / (a_separacion * B_ceil);
                if(longi_rejilla<0.7){
                    longi_rejilla = 0.7;
                }   
                
                /*Recalcular area neta*/               
                double area_neta_2 = (a_separacion / (a_separacion+barrotes/*esta variable no es la correcta*/)) * B_ceil * longi_rejilla; //posible error en la var barrotes
                n_ori = area_neta_2 / (a_separacion*B_ceil);
                n_ori = Math.ceil(n_ori);
                System.out.println("numero de orificios: " + n_ori);
                double area_neta_3 = a_separacion * B_ceil * n_ori;
                area_neta_3 = redondearDecimales(area_neta_3, 3);
                double v_barrotes_2 = qCaudal / (0.9 * area_neta_3);
                double longi_rejilla_2 = (area_neta_3 * (a_separacion + barrotes)) / (a_separacion * B_ceil);
                System.out.println("v_barrotes_2: " + v_barrotes_2);
                System.out.println("longi_rejilla_2: " + longi_rejilla_2);
                
                /*Niveles de agua*/
                longi_canal = longi_rejilla_2 + 0.3/*dato del ppt*/;
                profun_aguas_abajo = Math.pow((Math.pow(qCaudal, 2.0)/ (9.81 * Math.pow(B_ceil, 2.0))),(1.0/3.0));
                profun_critica = profun_aguas_abajo;
                profun_aguas_arriba = Math.pow((2 * Math.pow(profun_aguas_abajo, 2.0) + Math.pow(profun_aguas_abajo - (pendiente_i * longi_canal / 3.0),2.0)), (1.0/2.0)) - (2.0/3.0) * pendiente_i*longi_canal;
                System.out.println("he: " + profun_aguas_abajo);
                System.out.println("ho: " + profun_aguas_arriba);
                
                /*ALTURA TOTAL DE LOS MUROS DEL CANAL DE ADUCCION*/
                H0 = profun_aguas_arriba + bordeLibre;
                He = profun_aguas_abajo + (profun_aguas_arriba - profun_aguas_abajo) + pendiente_i * longi_canal + bordeLibre;
                System.out.println("H0: " + H0);
                System.out.println("He: " + He);
                
                vel_agua_final = qCaudal / (B_ceil * profun_aguas_abajo);
                if(0.3<vel_agua_final && vel_agua_final<3.0){
                    /*DISEÑO DE LA CÁMARA DE RECOLECCIÓN*/
                    double Xs_2 = 0.36 * Math.pow(vel_agua_final, (2.0/3.0)) + 0.6 * Math.pow(profun_aguas_abajo, (4.0/7.0));
                    double Xi_2 = 0.18 * Math.pow(vel_agua_final,(4.0/7.0)) + 0.74 * Math.pow(profun_aguas_abajo, (3.0/4.0));
                    B_camara = Xs_2 + 0.3;
                    B_camara = 1.5; ////////////////////////////////////////////////////////wtf/////////////////
                    System.out.println("Xs_2: " + Xs_2);
                    System.out.println("Xi_2: " + Xi_2);
                    System.out.println("B_camara: " + B_camara);
                    
                    /*ALTURA DE LOS MUROS DE CONTENCIÓN*/
                    H_muros = Math.pow((qmaximo / (1.84 * laterales)), (2.0/3.0));
                    H_muros = Math.ceil(H_muros);
                    System.out.println("H_muros: " + H_muros);
                    
                    /*CAUDAL DE EXCESOS*/
                    H = Math.pow((qProm / 1.84 * laterales), (2.0/3.0));
                    q_captado = coe_descarga * area_neta_3 * Math.sqrt(2 * 9.81 * H);                     
                    q_exce = q_captado - qCaudal;
                    System.out.println("q_exce: " + q_exce);
                    
                    /*CONDICIONES EN EL VERTEDERO DE EXCESOS*/
                    H_exce = Math.pow((q_exce / (1.84 * B_camara)),(2.0/3.0));
                    V_exce = q_exce / (H_exce * B_camara);
                    double e_Xs_esos = 0.36 * Math.pow(V_exce, (2.0/3.0)) + 0.6 * Math.pow(H_exce, (4.0/7.0)); 
                    System.out.println("e_Xs_esos: " + e_Xs_esos);
                }else{
                    JOptionPane.showMessageDialog(null,"Velocidad del agua al final del canal inferior o superior a la esperada.");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Velocidad del rio inferior o superior a la esperada.");
            }
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbTamaBarrotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTamaBarrotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTamaBarrotesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTamaBarrotes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCoe_descarga;
    private javax.swing.JTextField txtCota_entrega;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPendiente_i;
    private javax.swing.JTextField txtQ;
    private javax.swing.JTextField txtQmax;
    private javax.swing.JTextField txtQprom;
    private javax.swing.JTextField txtSeparacion;
    // End of variables declaration//GEN-END:variables
}
