/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_abasto;


import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.events.PdfDocumentEvent;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.List;
import com.itextpdf.layout.element.ListItem;
import com.itextpdf.layout.element.Paragraph;
import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import project_abasto.Project_abasto;


public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        this.setUndecorated(true);
        initComponents();
        this.setTitle("BocApp");
        this.setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0,0,this.getBounds().width, this.getBounds().height, 27, 27);
        AWTUtilities.setWindowShape(this, forma);
        lbl_fondo_aguas_arriba_3.setOpaque(true);
        
    }
    /*Datos de entrada*/
    String qCaudal_s, qProm_s,qmaximo_s, pendiente_i_s, coe_descarga_s, cota_entrega_s, barrotes_s, a_separacion_s, fondoRio_s;
    double qCaudal, qProm, qmaximo, pendiente_i, coe_descarga, cota_entrega, barrotes, a_separacion, fondoRio;
    /*DATOS*/
    double h_diseño, laterales=1, correc_laterales,corona_muros_contencion, v_rio, Xs, Xi, B, area_neta, v_barrotes=0.1, longi_rejilla,n_ori, profun_aguas_abajo/*he*/, profun_critica/*hc*/, 
            profun_aguas_arriba/*ho*/, He, H0, longi_canal, bordeLibre=0.15, vel_agua_final, B_camara, h_muros, altura_reservorio_exce, q_captado, q_exce, H_exce, V_exce, longi_rejilla_2;
    int n_ori_int, d_int;
    /*CALCULO DE COTAS*/    
    double diseño, maxima, promedio, fondo_aguas_arriba, fondo_aguas_abajo, lamina_aguas_arriba, lamina_aguas_abajo, Cresta_vertedero_excesos, fondo, cota_entrada, 
            cota_salida;
    
    public static double redondearDecimales(double valorInicial, int numeroDecimales) {
        double parteEntera, resultado;
        resultado = valorInicial;
        parteEntera = Math.floor(resultado);
        resultado=(resultado-parteEntera)*Math.pow(10, numeroDecimales);
        resultado=Math.round(resultado);
        resultado=(resultado/Math.pow(10, numeroDecimales))+parteEntera;
        return resultado;
    }
    java.util.Date fecha = new Date();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPendiente_i = new javax.swing.JTextField();
        txtQprom = new javax.swing.JTextField();
        txtQ = new javax.swing.JTextField();
        txtCoe_descarga = new javax.swing.JTextField();
        txtCota_entrega = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSeparacion = new javax.swing.JTextField();
        cmbTamaBarrotes = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtQmax = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFondoRio = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_maxima = new javax.swing.JLabel();
        lbl_lamina_aguas_abajo = new javax.swing.JLabel();
        lbl_diseño = new javax.swing.JLabel();
        lbl_fondoRio_s_2 = new javax.swing.JLabel();
        lbl_fondo_aguas_arriba_2 = new javax.swing.JLabel();
        lbl_promedio = new javax.swing.JLabel();
        lbl_corona_muros_contencion_2 = new javax.swing.JLabel();
        lbl_lamina_aguas_arriba = new javax.swing.JLabel();
        lbl_fondo_2 = new javax.swing.JLabel();
        lbl_fondo_aguas_abajo = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();
        lbl_fondo_aguas_arriba = new javax.swing.JLabel();
        lbl_fondoRio_s = new javax.swing.JLabel();
        lbl_corona_muros_contencion = new javax.swing.JLabel();
        lbl_lamina_aguas_arriba_2 = new javax.swing.JLabel();
        lbl_fondoRio_s_3 = new javax.swing.JLabel();
        lbl_lamina_aguas_abajo_2 = new javax.swing.JLabel();
        lbl_fondo_3 = new javax.swing.JLabel();
        lbl_fondo_aguas_abajo_2 = new javax.swing.JLabel();
        lblTam_barro = new javax.swing.JLabel();
        lbl_N = new javax.swing.JLabel();
        lblLr = new javax.swing.JLabel();
        lbl_B = new javax.swing.JLabel();
        lbl_d = new javax.swing.JLabel();
        lbl_bordeLibre = new javax.swing.JLabel();
        lbl_profun_aguas_arriba = new javax.swing.JLabel();
        lbl_H0 = new javax.swing.JLabel();
        lbl_fondo_aguas_arriba_3 = new javax.swing.JLabel();
        lbl_fondoRio_s_4 = new javax.swing.JLabel();
        lbl_pendiente_i = new javax.swing.JLabel();
        lbl_correc_laterales = new javax.swing.JLabel();
        lbl_correc_laterales1 = new javax.swing.JLabel();
        lbl_bordeLibre_2 = new javax.swing.JLabel();
        lbl_iL = new javax.swing.JLabel();
        lbl_ho_he = new javax.swing.JLabel();
        lbl_He = new javax.swing.JLabel();
        lbl_profun_aguas_abajo = new javax.swing.JLabel();
        lbl_fondo_aguas_abajo_3 = new javax.swing.JLabel();
        lblL = new javax.swing.JLabel();
        lblImg1 = new javax.swing.JLabel();
        lblImg2 = new javax.swing.JLabel();
        lblImg3 = new javax.swing.JLabel();
        lblImg4 = new javax.swing.JLabel();
        lblImg5 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jButton3 = new javax.swing.JButton();
        cmbDep = new javax.swing.JComboBox<>();
        cmbProvin = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(76, 77, 98));
        setPreferredSize(new java.awt.Dimension(1310, 720));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(1280, 730));

        jPanel1.setBackground(new java.awt.Color(181, 173, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 4700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Provincia:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Coeficiente de descarga (Cd):");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cota del río en la entrega:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Caudal (Q):");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Caudal promedio (Qprom):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pendiente del fondo del canal (i):");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        txtPendiente_i.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPendiente_iKeyTyped(evt);
            }
        });
        jPanel1.add(txtPendiente_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 84, -1));

        txtQprom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQpromKeyTyped(evt);
            }
        });
        jPanel1.add(txtQprom, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 84, -1));

        txtQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQActionPerformed(evt);
            }
        });
        txtQ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQKeyTyped(evt);
            }
        });
        jPanel1.add(txtQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 84, -1));

        txtCoe_descarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCoe_descargaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCoe_descarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 84, -1));

        txtCota_entrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCota_entregaKeyTyped(evt);
            }
        });
        jPanel1.add(txtCota_entrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 84, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Diametro de barrotes:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Separación entre barrotes:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        txtSeparacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSeparacionKeyTyped(evt);
            }
        });
        jPanel1.add(txtSeparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 84, -1));

        cmbTamaBarrotes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/2\"", "3/4\"", "1\"" }));
        cmbTamaBarrotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTamaBarrotesActionPerformed(evt);
            }
        });
        jPanel1.add(cmbTamaBarrotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 84, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("cm.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("L/s");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel12.setText("%");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Caudal maximo (Qmax):");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txtQmax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQmaxKeyTyped(evt);
            }
        });
        jPanel1.add(txtQmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 84, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel14.setText("m³/s");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel15.setText("m³/s");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Fondo del río en la captación:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        txtFondoRio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFondoRioKeyTyped(evt);
            }
        });
        jPanel1.add(txtFondoRio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 84, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("m.");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Fecha:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel19.setText("m.");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setText("Generar PDF");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 4540, 180, 50));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Departamento:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        jLabel20.setText("1.00");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1440, 30, 30));

        lbl_maxima.setForeground(new java.awt.Color(255, 0, 0));
        lbl_maxima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_maxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 2200, 50, 20));

        lbl_lamina_aguas_abajo.setForeground(new java.awt.Color(255, 0, 0));
        lbl_lamina_aguas_abajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_lamina_aguas_abajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 2440, 50, 20));

        lbl_diseño.setForeground(new java.awt.Color(255, 0, 0));
        lbl_diseño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_diseño, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 2320, 50, 30));

        lbl_fondoRio_s_2.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fondoRio_s_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_fondoRio_s_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 2370, 50, 20));

        lbl_fondo_aguas_arriba_2.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fondo_aguas_arriba_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_fondo_aguas_arriba_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 2410, 40, 20));

        lbl_promedio.setForeground(new java.awt.Color(255, 0, 0));
        lbl_promedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_promedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 2270, 50, 30));

        lbl_corona_muros_contencion_2.setForeground(new java.awt.Color(255, 0, 0));
        lbl_corona_muros_contencion_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_corona_muros_contencion_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 2150, 50, 20));

        lbl_lamina_aguas_arriba.setForeground(new java.awt.Color(255, 0, 0));
        lbl_lamina_aguas_arriba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_lamina_aguas_arriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 2470, 50, 20));

        lbl_fondo_2.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fondo_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_fondo_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 2570, 50, 20));

        lbl_fondo_aguas_abajo.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fondo_aguas_abajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_fondo_aguas_abajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 2450, 50, 20));

        lbl_fondo.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 1810, 50, 20));

        lbl_fondo_aguas_arriba.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fondo_aguas_arriba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_fondo_aguas_arriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 1660, 50, 20));

        lbl_fondoRio_s.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fondoRio_s.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_fondoRio_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1550, 40, 20));

        lbl_corona_muros_contencion.setForeground(new java.awt.Color(255, 0, 0));
        lbl_corona_muros_contencion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_corona_muros_contencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 1330, 50, 30));

        lbl_lamina_aguas_arriba_2.setForeground(new java.awt.Color(255, 0, 0));
        lbl_lamina_aguas_arriba_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_lamina_aguas_arriba_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 3220, 50, 30));

        lbl_fondoRio_s_3.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fondoRio_s_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_fondoRio_s_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 3060, 50, 20));

        lbl_lamina_aguas_abajo_2.setForeground(new java.awt.Color(255, 0, 0));
        lbl_lamina_aguas_abajo_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_lamina_aguas_abajo_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 3270, 50, 20));

        lbl_fondo_3.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fondo_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_fondo_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 3400, 50, 30));

        lbl_fondo_aguas_abajo_2.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fondo_aguas_abajo_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_fondo_aguas_abajo_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 3160, 50, 30));

        lblTam_barro.setBackground(new java.awt.Color(0, 0, 0));
        lblTam_barro.setForeground(new java.awt.Color(255, 0, 0));
        lblTam_barro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblTam_barro, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 750, 30, 20));

        lbl_N.setBackground(new java.awt.Color(0, 0, 0));
        lbl_N.setForeground(new java.awt.Color(255, 0, 0));
        lbl_N.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_N, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 760, 40, 20));

        lblLr.setBackground(new java.awt.Color(0, 0, 0));
        lblLr.setForeground(new java.awt.Color(255, 0, 0));
        lblLr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblLr, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 770, 40, 30));

        lbl_B.setBackground(new java.awt.Color(0, 0, 0));
        lbl_B.setForeground(new java.awt.Color(255, 0, 0));
        lbl_B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, 40, 20));

        lbl_d.setForeground(new java.awt.Color(255, 0, 0));
        lbl_d.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 950, 40, 20));

        lbl_bordeLibre.setForeground(new java.awt.Color(255, 0, 0));
        lbl_bordeLibre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_bordeLibre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 3910, 40, 20));

        lbl_profun_aguas_arriba.setForeground(new java.awt.Color(255, 0, 0));
        lbl_profun_aguas_arriba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_profun_aguas_arriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 4010, 40, 20));

        lbl_H0.setForeground(new java.awt.Color(255, 0, 0));
        lbl_H0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_H0, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 3970, 40, 20));

        lbl_fondo_aguas_arriba_3.setBackground(new java.awt.Color(255, 255, 255));
        lbl_fondo_aguas_arriba_3.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fondo_aguas_arriba_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_fondo_aguas_arriba_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 4050, 40, 20));

        lbl_fondoRio_s_4.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fondoRio_s_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_fondoRio_s_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 3840, 40, 20));

        lbl_pendiente_i.setForeground(new java.awt.Color(255, 0, 0));
        lbl_pendiente_i.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_pendiente_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 4130, 40, 20));

        lbl_correc_laterales.setForeground(new java.awt.Color(255, 0, 0));
        lbl_correc_laterales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_correc_laterales, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 3800, 40, 20));

        lbl_correc_laterales1.setForeground(new java.awt.Color(255, 0, 0));
        lbl_correc_laterales1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_correc_laterales1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 4190, 40, 20));

        lbl_bordeLibre_2.setForeground(new java.awt.Color(255, 0, 0));
        lbl_bordeLibre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_bordeLibre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 3910, 40, 20));

        lbl_iL.setForeground(new java.awt.Color(255, 0, 0));
        lbl_iL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_iL, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 4000, 40, 20));

        lbl_ho_he.setForeground(new java.awt.Color(255, 0, 0));
        lbl_ho_he.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_ho_he, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 4080, 40, 20));

        lbl_He.setForeground(new java.awt.Color(255, 0, 0));
        lbl_He.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_He, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 4030, 40, 20));

        lbl_profun_aguas_abajo.setForeground(new java.awt.Color(255, 0, 0));
        lbl_profun_aguas_abajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_profun_aguas_abajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 4140, 40, 20));

        lbl_fondo_aguas_abajo_3.setForeground(new java.awt.Color(255, 0, 0));
        lbl_fondo_aguas_abajo_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_fondo_aguas_abajo_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 4140, 40, 20));

        lblL.setBackground(new java.awt.Color(255, 0, 0));
        lblL.setForeground(new java.awt.Color(255, 0, 0));
        lblL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblL, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 2490, 60, 20));

        lblImg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plano 1 - PDF.png"))); // NOI18N
        lblImg1.setToolTipText("");
        lblImg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1270, 790));

        lblImg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plano 2 - PDF.png"))); // NOI18N
        lblImg2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1260, 1260, 780));

        lblImg3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plano 3 - PDF.png"))); // NOI18N
        lblImg3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2080, 1270, 780));

        lblImg4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plano 4 - PDF.png"))); // NOI18N
        lblImg4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2870, 1260, -1));

        lblImg5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plano 5 - PDF.png"))); // NOI18N
        lblImg5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3700, 1260, 780));

        jCalendar1.setMaxSelectableDate(fecha);
        jPanel1.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 220));

        jButton3.setBackground(new java.awt.Color(175, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, -1, -1));

        cmbDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amazonas", "Áncash", "Apurímac", "Arequipa", "Ayacucho", "Cajamarca", "Callao", "Cusco", "Huancavelica", "Huánuco", "Ica", "Junín", "La Libertad", "Lambayeque", "Lima", "Loreto", "Madre de Dios", "Moquegua", "Pasco", "Piura", "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali" }));
        cmbDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepActionPerformed(evt);
            }
        });
        jPanel1.add(cmbDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 180, -1));

        jPanel1.add(cmbProvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 180, -1));

        jLabel24.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Ing. Fernando Paz Zagaceta ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 420, -1, -1));

        lblFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pruebas-de-presion.jpg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 820));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pruebas-de-presion.jpg"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4080, 1300, 620));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{
        if(txtQ.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor del caudal de diseño.");
        }else if (txtSeparacion.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca la separación entre barrotes.");
        }else if(txtPendiente_i.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca la pendiente del fondo del canal.");
        }else if(txtQmax.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor del caudal maximo.");
        }else if(txtQprom.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor del caudal promedio.");
        }else if(txtCoe_descarga.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor del coeficiente de descarga.");
        }else if(txtCota_entrega.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor de la Cota de entrega.");
        }else if(txtFondoRio.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Introduzca el valor del fondo del río.");
        }else{
            int n_deci = 2;
            
            qCaudal_s= txtQ.getText();
            qCaudal = Double.parseDouble(qCaudal_s);
            qCaudal = qCaudal/1000.0;
            
            barrotes_s = (String) cmbTamaBarrotes.getSelectedItem();
            switch (barrotes_s) {
                case "1/2\"":
                    barrotes = 0.0127;
                    break;
                case "3/4\"":
                    barrotes = 0.01905;
                    break;
                case "1\"":                
                    barrotes = 0.0254;
                    break;
                default:
                    JOptionPane.showMessageDialog(rootPane, "barrotes 0??????");
                    break;
            }
            
            a_separacion_s = txtSeparacion.getText();
            a_separacion = Double.parseDouble(a_separacion_s);
            a_separacion = a_separacion /100.0;   
            
            pendiente_i_s = txtPendiente_i.getText();
            pendiente_i = Double.parseDouble(pendiente_i_s);
            pendiente_i = pendiente_i / 100.0;
            
            qmaximo_s = txtQmax.getText();
            qmaximo = Double.parseDouble(qmaximo_s);
            
            qProm_s = txtQprom.getText();
            qProm = Double.parseDouble(qProm_s);
            
            coe_descarga_s = txtCoe_descarga.getText();
            coe_descarga = Double.parseDouble(coe_descarga_s);
            
            cota_entrega_s = txtCota_entrega.getText();
            cota_entrega = Double.parseDouble(cota_entrega_s);
            
            fondoRio_s = txtFondoRio.getText();
            fondoRio = Double.parseDouble(fondoRio_s);
            
            /* profun lamina de agua */
            h_diseño = Math.pow((qCaudal / 1.84 * laterales), (2.0/3.0));
            System.out.println("H: " + h_diseño);
            
            /* correción contracciones */
            correc_laterales = laterales - 0.2 * h_diseño;
            System.out.println("L': " + correc_laterales);
            
            /*velocidad del río sobre la presa*/
            v_rio = qCaudal / (correc_laterales * h_diseño); 
            System.out.println("V: "+v_rio);
            
            if(0.3<v_rio && v_rio<3.0){
                System.out.println("ok");
                Xs = 0.36 * Math.pow(v_rio,(2.0/3.0)) + 0.6 * Math.pow(h_diseño,(4.0/7.0));
                Xi = 0.18 * Math.pow(v_rio,(4.0/7.0)) + 0.74 * Math.pow(h_diseño,(3.0/4.0));
                B = Xs + 0.1;
                double B_ceil = redondearDecimales(B, 1);
                System.out.println("Xs: " + Xs);
                System.out.println("Xi: " + Xi);
                System.out.println("B: " + B_ceil);
                
                area_neta = qCaudal / (0.9 * v_barrotes);
                longi_rejilla = (area_neta * (a_separacion + barrotes)) / (a_separacion * B_ceil);
                if(longi_rejilla<0.7){
                    longi_rejilla = 0.7;
                }   
                
                /*Recalcular area neta*/               
                double area_neta_2 = (a_separacion / (a_separacion+barrotes)) * B_ceil * longi_rejilla;
                n_ori = area_neta_2 / (a_separacion*B_ceil);
                n_ori_int =(int) Math.ceil(n_ori);
                System.out.println("numero de orificios: " + n_ori_int);
                double area_neta_3 = a_separacion * B_ceil * n_ori_int;
                area_neta_3 = redondearDecimales(area_neta_3, 3);
                double v_barrotes_2 = qCaudal / (0.9 * area_neta_3);
                longi_rejilla_2 = (area_neta_3 * (a_separacion + barrotes)) / (a_separacion * B_ceil);
                System.out.println("v_barrotes_2: " + v_barrotes_2);
                System.out.println("longi_rejilla_2: " + longi_rejilla_2);
                
                /*Niveles de agua*/
                longi_canal = longi_rejilla_2 + 0.3/*dato del ppt*/;
                profun_aguas_abajo = Math.pow((Math.pow(qCaudal, 2.0)/ (9.81 * Math.pow(B_ceil, 2.0))),(1.0/3.0));
                profun_critica = profun_aguas_abajo;
                profun_aguas_arriba = Math.pow((2 * Math.pow(profun_aguas_abajo, 2.0) + Math.pow(profun_aguas_abajo - (pendiente_i * longi_canal / 3.0),2.0)), (1.0/2.0)) - (2.0/3.0) * pendiente_i*longi_canal;
                System.out.println("he: " + profun_aguas_abajo);
                System.out.println("ho: " + profun_aguas_arriba);
                
                /*ALTURA TOTAL DE LOS MUROS DEL CANAL DE ADUCCION*/
                H0 = profun_aguas_arriba + bordeLibre;
                He = profun_aguas_abajo + (profun_aguas_arriba - profun_aguas_abajo) + pendiente_i * longi_canal + bordeLibre;
                System.out.println("H0: " + H0);
                System.out.println("He: " + He);
                
                vel_agua_final = qCaudal / (B_ceil * profun_aguas_abajo);
                if(0.3<vel_agua_final && vel_agua_final<3.0){
                    /*DISEÑO DE LA CÁMARA DE RECOLECCIÓN*/
                    double Xs_2 = 0.36 * Math.pow(vel_agua_final, (2.0/3.0)) + 0.6 * Math.pow(profun_aguas_abajo, (4.0/7.0));
                    double Xi_2 = 0.18 * Math.pow(vel_agua_final,(4.0/7.0)) + 0.74 * Math.pow(profun_aguas_abajo, (3.0/4.0));
                    B_camara = Xs_2 + 0.3;
                    if(B_camara<1.5){
                        B_camara = 1.5;
                    }
                    System.out.println("Xs_2: " + Xs_2);
                    System.out.println("Xi_2: " + Xi_2);
                    System.out.println("B_camara: " + B_camara);
                    
                    /*ALTURA DE LOS MUROS DE CONTENCIÓN*/
                    h_muros = Math.pow((qmaximo / (1.84 * laterales)), (2.0/3.0));
                    System.out.println("H_muros: " + h_muros);
                    
                    /*CAUDAL DE EXCESOS*/
                    altura_reservorio_exce = Math.pow((qProm / 1.84 * laterales), (2.0/3.0));
                    q_captado = coe_descarga * area_neta_3 * Math.sqrt(2 * 9.81 * altura_reservorio_exce);                     
                    q_exce = q_captado - qCaudal;
                    System.out.println("q_exce: " + q_exce);
                    
                    /*CONDICIONES EN EL VERTEDERO DE EXCESOS*/
                    H_exce = Math.pow((q_exce / (1.84 * B_camara)),(2.0/3.0));
                    V_exce = q_exce / (H_exce * B_camara);
                    double e_Xs_esos = 0.36 * Math.pow(V_exce, (2.0/3.0)) + 0.6 * Math.pow(H_exce, (4.0/7.0)); 
                    System.out.println("e_Xs_esos: " + e_Xs_esos);
                    
                    /*CALCULO DE COTAS*/
                    /*lamina sobre la presa*/
                    diseño = fondoRio + h_diseño;
                    maxima = fondoRio + h_muros;
                    promedio = fondoRio + altura_reservorio_exce;
                    /*Corona de los muros de contención*/
                    corona_muros_contencion = fondoRio + 1;
                    /*Canal de aducción*/
                    fondo_aguas_arriba = fondoRio - H0;
                    fondo_aguas_abajo = fondoRio - He;
                    lamina_aguas_arriba = (fondoRio - H0) + profun_aguas_arriba;
                    lamina_aguas_abajo = (fondoRio - He) + profun_aguas_abajo;
                    /*Camara de recolección*/
                    Cresta_vertedero_excesos = fondoRio - He - bordeLibre;
                    fondo = fondoRio - He - bordeLibre - 0.6;
                    /*Tuberia de excesos*/
                    cota_entrada = fondo;
                    cota_salida = cota_entrega + coe_descarga/*es esta variablñe correcta?*/;
                    
                    /*CALCULO TUBERIA DE EXCESOS*/
                    double j = (cota_entrada - cota_salida) / 50;
                    System.out.println("j:" + j);
                    double d = Math.pow((q_exce / (0.2785 * /*C*/100 * Math.pow(j, 0.54))),(1.0/2.63)); //que es C?? por ahora es 100
                    d = d * 39.3701;
                    d_int = (int) Math.ceil(d);
                    System.out.println("d\":" + d_int);
                    
                    double ho_he, iL;
                    ho_he = profun_aguas_arriba - profun_aguas_abajo;
                    iL = pendiente_i*correc_laterales;
                    
                    if(B_camara == 0 || longi_rejilla_2 == 0 || fondo_aguas_arriba == 0 || fondo == 0 || maxima == 0 || promedio == 0 || diseño == 0 || fondo_aguas_arriba == 0 || 
                            fondo_aguas_abajo == 0 || lamina_aguas_abajo == 0 || lamina_aguas_arriba == 0 || correc_laterales == 0 || H0 == 0 || profun_aguas_arriba == 0 || 
                            profun_aguas_abajo == 0 || ho_he == 0 || iL == 0 || He == 0 || d_int == 0){
                        JOptionPane.showMessageDialog(null, "Valores no admisibles.", "Valor de 0", JOptionPane.ERROR_MESSAGE);                     
                    }else if(B_camara < 0 || longi_rejilla_2 < 0 || fondo_aguas_arriba < 0 || fondo < 0 || maxima < 0 || promedio < 0 || diseño < 0 || fondo_aguas_arriba < 0 || 
                            fondo_aguas_abajo < 0 || lamina_aguas_abajo < 0 || lamina_aguas_arriba < 0 || correc_laterales < 0 || H0 < 0 || profun_aguas_arriba < 0 || 
                            profun_aguas_abajo < 0 || ho_he < 0 || iL < 0 || He < 0 || d_int < 0){
                        JOptionPane.showMessageDialog(null, "Valores no admisibles.", "Valor negativo", JOptionPane.ERROR_MESSAGE); 
                    }else{
                        /*PONER DATOS EN LA IMAGEN REDONDEADOS A 2 DECIMALES*/
                        //Plano1
                        B_camara = redondearDecimales(B_camara, n_deci);
                        longi_rejilla_2 = redondearDecimales(longi_rejilla_2, n_deci);
                        lbl_d.setText(d_int+"\"");                   
                        lbl_B.setText(B_camara+"");
                        lbl_N.setText(n_ori_int+"");                  
                        lblLr.setText(longi_rejilla_2+"");
                        lblTam_barro.setText(barrotes_s);

                        //Plano 2
                        fondo_aguas_arriba = redondearDecimales(fondo_aguas_arriba, n_deci);
                        fondo = redondearDecimales(fondo, 2);
                        System.out.println("fondo_aguas_arriba:" + fondo_aguas_arriba);
                        
                        lbl_corona_muros_contencion.setText(corona_muros_contencion+"");
                        lbl_fondoRio_s.setText(fondoRio_s+"");
                        lbl_fondo_aguas_arriba.setText(fondo_aguas_arriba+"");
                        lbl_fondo.setText(fondo+"");

                        //Plano 3
                        maxima = redondearDecimales(maxima, n_deci);
                        promedio = redondearDecimales(promedio, n_deci);
                        diseño = redondearDecimales(diseño, n_deci);
                        fondo_aguas_arriba = redondearDecimales(fondo_aguas_arriba, n_deci);
                        fondo_aguas_abajo = redondearDecimales(fondo_aguas_abajo, n_deci);
                        lamina_aguas_abajo = redondearDecimales(lamina_aguas_abajo, n_deci);
                        lamina_aguas_arriba = redondearDecimales(lamina_aguas_arriba, n_deci);
                        correc_laterales = redondearDecimales(correc_laterales, n_deci);

                        lbl_corona_muros_contencion_2.setText(corona_muros_contencion+"");
                        lbl_maxima.setText(maxima+"");
                        lbl_promedio.setText(promedio+"");
                        lbl_diseño.setText(diseño+"");
                        lbl_fondoRio_s_2.setText(fondoRio_s+"");
                        lbl_fondo_aguas_arriba_2.setText(fondo_aguas_arriba+"");
                        lbl_fondo_aguas_abajo.setText(fondo_aguas_abajo+"");  
                        lbl_lamina_aguas_abajo.setText(lamina_aguas_abajo+"");        
                        lbl_lamina_aguas_arriba.setText(lamina_aguas_arriba+"");       
                        lbl_fondo_2.setText(fondo+""); 
                        lblL.setText(correc_laterales+"");

                        //Plano 4                    
                        lbl_fondoRio_s_3.setText(fondoRio_s);
                        lbl_fondo_aguas_abajo_2.setText(fondo_aguas_abajo+"");
                        lbl_lamina_aguas_arriba_2.setText(lamina_aguas_arriba+"");
                        lbl_lamina_aguas_abajo_2.setText(lamina_aguas_abajo+"");
                        lbl_fondo_3.setText(fondo+""); 

                        //Plano 5                        
                        H0 = redondearDecimales(H0, n_deci);
                        profun_aguas_arriba = redondearDecimales(profun_aguas_arriba, n_deci);
                        profun_aguas_abajo = redondearDecimales(profun_aguas_abajo, n_deci);
                        ho_he= redondearDecimales(ho_he, n_deci);
                        iL =redondearDecimales(iL, n_deci);
                        He= redondearDecimales(He, n_deci);

                        lbl_fondoRio_s_4.setText(fondoRio_s);
                        lbl_bordeLibre.setText(bordeLibre+"");   
                        lbl_H0.setText(H0+"");        
                        lbl_profun_aguas_arriba.setText(profun_aguas_arriba+"");        
                        lbl_fondo_aguas_arriba_3.setText(fondo_aguas_arriba+"");
                        lbl_pendiente_i.setText(pendiente_i_s+"%");
                        lbl_correc_laterales.setText(correc_laterales+"");
                        lbl_correc_laterales1.setText(correc_laterales+"");
                        lbl_bordeLibre_2.setText(bordeLibre+"");
                        lbl_iL.setText(iL+"");
                        lbl_ho_he.setText(ho_he+"");
                        lbl_profun_aguas_abajo.setText(profun_aguas_abajo+"");  
                        lbl_fondo_aguas_abajo_3.setText(fondo_aguas_abajo+"");      
                        lbl_He.setText(He+"");  
                    }                                       
                }else{
                    JOptionPane.showMessageDialog(null,"Velocidad del agua al final del canal inferior o superior a la esperada.");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Velocidad del rio inferior o superior a la esperada.");
            }           
        }
    }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: " + e);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbTamaBarrotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTamaBarrotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTamaBarrotesActionPerformed

    private void txtQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQActionPerformed
    }//GEN-LAST:event_txtQActionPerformed

    private void txtQKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQKeyTyped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo números");
        }
    }//GEN-LAST:event_txtQKeyTyped

    private void txtQpromKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQpromKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo números");
        }
    }//GEN-LAST:event_txtQpromKeyTyped

    private void txtQmaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQmaxKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo números");
        }
    }//GEN-LAST:event_txtQmaxKeyTyped

    private void txtPendiente_iKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPendiente_iKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo números");
        }
    }//GEN-LAST:event_txtPendiente_iKeyTyped

    private void txtCoe_descargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCoe_descargaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo números");
        }
    }//GEN-LAST:event_txtCoe_descargaKeyTyped

    private void txtCota_entregaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCota_entregaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo números");
        }
    }//GEN-LAST:event_txtCota_entregaKeyTyped

    private void txtSeparacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeparacionKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo números");
        }
    }//GEN-LAST:event_txtSeparacionKeyTyped

    private void txtFondoRioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFondoRioKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo números");
        }
    }//GEN-LAST:event_txtFondoRioKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepActionPerformed
        // TODO add your handling code here:
        Project_abasto.Provincia();
    }//GEN-LAST:event_cmbDepActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(cmbProvin.getSelectedItem()==null){
            JOptionPane.showMessageDialog(null,"Introduzca la provincia.");
        }else{
            String dia=Integer.toString(jCalendar1.getCalendar().get(Calendar.DAY_OF_MONTH));
            String mes=Integer.toString(jCalendar1.getCalendar().get(Calendar.MONTH));
            String año=Integer.toString(jCalendar1.getCalendar().get(Calendar.YEAR));
            String fechas=dia+"/"+mes+"/"+año;
            int height = (int) PageSize.A4.getWidth();
            int width = (int) PageSize.A4.getHeight();
            String ubicacion = "Departamento: " + cmbDep.getSelectedItem().toString() + " Provincia: " + cmbProvin.getSelectedItem().toString();
            String ruta_plano_1 = "src\\imagenes\\Plano 1 - var.png";
            String ruta_plano_2 = "src\\imagenes\\Plano 2 - var.png";
            String ruta_plano_3 = "src\\imagenes\\Plano 3 - var.png";
            String ruta_plano_4 = "src\\imagenes\\Plano 4 - var.png";
            String ruta_plano_5 = "src\\imagenes\\Plano 5 - var.png";
            String logo_img = "src\\imagenes\\logo_usmp.png";
            try{
                String ruta_user= System.getProperty("user.home");
                PageSize pagesize = new PageSize( width, height );
                String DesGuardado = ruta_user+"\\Desktop"+"\\"+cmbDep.getSelectedItem().toString()+".pdf";
                PdfWriter EscribirPDF = new PdfWriter(DesGuardado);
                PdfDocument DocumentoPDF = new PdfDocument(EscribirPDF);          
                Document documento = new Document(DocumentoPDF, pagesize);
                Cabecera cabeceraD = new Cabecera(documento, ubicacion, fechas);

                DocumentoPDF.addEventHandler(PdfDocumentEvent.END_PAGE, cabeceraD);
                documento.setMargins(60, 21, 60, 31);
                
                Image logo=new Image(ImageDataFactory.create(logo_img));
                logo.scaleToFit(75,86);
                logo.setFixedPosition(715, 505);
                documento.add(logo);
                
                Paragraph titulo = new Paragraph();
                titulo.add("Fórmulas");
                List formulas_lista=new List().setSymbolIndent(12).setListSymbol("-");
                formulas_lista.add(new ListItem("Caudal máximo: "))
                        .add("Lamina de agua en las condiciones de diseño: ")
                        .add("Corrección por las contracciones laterales: ")
                        .add("Velocidad del río sobre la presa: ")
                        .add("Ancho del canal de aducción: ")
                        .add("Área neta: ")
                        .add("Longitud rejilla: ")
                        .add("Recalcular área neta: ")
                        .add("Velocidad entre los barrotes: ")
                        .add("Longitud rejilla 2:")
                        .add("Profundidad aguas abajo: ")
                        .add("Profundidad aguas arriba: ")
                        .add("H0: ")
                        .add("He: ")
                        .add("Xi_2: ")
                        .add("B Cámara: ")
                        .add("Altura de los muros de contención: ")
                        .add("Caudal captado: ")
                        .add("Caudal de excesos: ")
                        .add("Vertedero de excesos: ")
                        .add("Lámina sobre la presa"
                                + "\nDiseño: "
                                + "\nMaxima: "
                                + "\nPromedio: ")
                        .add("Corona de los muros de contención: ")
                        .add("Canal de aducción"
                                + "\nFondo aguas arriba: "
                                + "\nFondo aguas abajo: "
                                + "\nLámina de aguas arriba: "
                                + "\nLámina de aguas abajo: ")
                        .add("Cámara de recolección"
                                + "\nCresta del vertedero de excesos: "
                                + "\nFondo: ")
                        .add("Tuberias de excesos"
                                + "\nCota de entrada: "
                                + "\nCota del río en la entrega: "
                                + "\nCota de salida: ")
                        .add("J: ")
                        .add("D: ");           
                
                documento.add(titulo);
                documento.add(formulas_lista);

                Image plano1=new Image(ImageDataFactory.create(ruta_plano_1));
                plano1.scaleToFit(630,515);
                List plano1_var=new List().setSymbolIndent(12).setListSymbol("-");
                plano1_var.add(new ListItem("Lr:"+ longi_rejilla_2))
                        .add("n: " +n_ori_int)
                        .add("Barrotes: "+barrotes_s)
                        .add("D: " + d_int)
                        .add("B: " + B_camara);
                plano1_var.setRelativePosition(631, 0, 0, 395);
                documento.add(plano1);
                documento.add(plano1_var);                                       
                              
                Image plano2=new Image(ImageDataFactory.create(ruta_plano_2));
                plano2.scaleToFit(630,515);
                documento.add(plano2);
                
                Image plano3=new Image(ImageDataFactory.create(ruta_plano_3));
                plano3.scaleToFit(630,515);
                documento.add(plano3);
                
                Image plano4=new Image(ImageDataFactory.create(ruta_plano_4));
                plano4.scaleToFit(630,515);
                documento.add(plano4);
                
                Image plano5=new Image(ImageDataFactory.create(ruta_plano_5));
                plano5.scaleToFit(630,515);
                documento.add(plano5);
                
                
                documento.close();
                JOptionPane.showMessageDialog(null, "Se ha generado en "+ ruta_user + "\\Desktop");
            }catch(Exception e){
                System.out.println("Error: ------>"+e);
            }
        }
            
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cmbDep;
    public static javax.swing.JComboBox<String> cmbProvin;
    private javax.swing.JComboBox<String> cmbTamaBarrotes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblImg1;
    private javax.swing.JLabel lblImg2;
    private javax.swing.JLabel lblImg3;
    private javax.swing.JLabel lblImg4;
    private javax.swing.JLabel lblImg5;
    private javax.swing.JLabel lblL;
    private javax.swing.JLabel lblLr;
    private javax.swing.JLabel lblTam_barro;
    private javax.swing.JLabel lbl_B;
    private javax.swing.JLabel lbl_H0;
    private javax.swing.JLabel lbl_He;
    private javax.swing.JLabel lbl_N;
    private javax.swing.JLabel lbl_bordeLibre;
    private javax.swing.JLabel lbl_bordeLibre_2;
    private javax.swing.JLabel lbl_corona_muros_contencion;
    private javax.swing.JLabel lbl_corona_muros_contencion_2;
    private javax.swing.JLabel lbl_correc_laterales;
    private javax.swing.JLabel lbl_correc_laterales1;
    private javax.swing.JLabel lbl_d;
    private javax.swing.JLabel lbl_diseño;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_fondoRio_s;
    private javax.swing.JLabel lbl_fondoRio_s_2;
    private javax.swing.JLabel lbl_fondoRio_s_3;
    private javax.swing.JLabel lbl_fondoRio_s_4;
    private javax.swing.JLabel lbl_fondo_2;
    private javax.swing.JLabel lbl_fondo_3;
    private javax.swing.JLabel lbl_fondo_aguas_abajo;
    private javax.swing.JLabel lbl_fondo_aguas_abajo_2;
    private javax.swing.JLabel lbl_fondo_aguas_abajo_3;
    private javax.swing.JLabel lbl_fondo_aguas_arriba;
    private javax.swing.JLabel lbl_fondo_aguas_arriba_2;
    private javax.swing.JLabel lbl_fondo_aguas_arriba_3;
    private javax.swing.JLabel lbl_ho_he;
    private javax.swing.JLabel lbl_iL;
    private javax.swing.JLabel lbl_lamina_aguas_abajo;
    private javax.swing.JLabel lbl_lamina_aguas_abajo_2;
    private javax.swing.JLabel lbl_lamina_aguas_arriba;
    private javax.swing.JLabel lbl_lamina_aguas_arriba_2;
    private javax.swing.JLabel lbl_maxima;
    private javax.swing.JLabel lbl_pendiente_i;
    private javax.swing.JLabel lbl_profun_aguas_abajo;
    private javax.swing.JLabel lbl_profun_aguas_arriba;
    private javax.swing.JLabel lbl_promedio;
    private javax.swing.JTextField txtCoe_descarga;
    private javax.swing.JTextField txtCota_entrega;
    private javax.swing.JTextField txtFondoRio;
    private javax.swing.JTextField txtPendiente_i;
    private javax.swing.JTextField txtQ;
    private javax.swing.JTextField txtQmax;
    private javax.swing.JTextField txtQprom;
    private javax.swing.JTextField txtSeparacion;
    // End of variables declaration//GEN-END:variables
}
